/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import qlks.dao.ThemPhongDao;
import qlks.entity.Phong;

/**
 *
 * @author CNG;
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeView() throws IOException, ClassNotFoundException {
        initComponents();
        //this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //changeColor(jPanel1);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        themPhongjButton = new javax.swing.JButton();
        suajButton = new javax.swing.JButton();
        datPhongjButton = new javax.swing.JButton();
        taoHoaDonjButton = new javax.swing.JButton();
        thoatjButton = new javax.swing.JButton();
        allRoomjButton = new javax.swing.JButton();
        xemHoaDonjButton = new javax.swing.JButton();
        searchjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        phongTrongjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        QuanLyPhongjMenu = new javax.swing.JMenu();
        ThemPhongjMenuItem = new javax.swing.JMenuItem();
        suaXoaPhongjMenuItem = new javax.swing.JMenuItem();
        XemThongTinjMenu = new javax.swing.JMenu();
        donDatPhongjMenuItem = new javax.swing.JMenuItem();
        allRoomjMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        datPhongjMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        xemHoaDonjMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        trangTimKiemjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        exitjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đặt phòng khách sạn");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        themPhongjButton.setBackground(new java.awt.Color(51, 154, 202));
        themPhongjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        themPhongjButton.setForeground(new java.awt.Color(51, 51, 0));
        themPhongjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Hopstarter-Button-Button-Add.24.png"));
        themPhongjButton.setText("   Thêm phòng  ");
        themPhongjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                themPhongjButtonMouseEntered(evt);
            }
        });

        suajButton.setBackground(new java.awt.Color(51, 154, 202));
        suajButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        suajButton.setForeground(new java.awt.Color(51, 51, 0));
        suajButton.setIcon(new javax.swing.ImageIcon("icon\\\\Hopstarter-Button-Button-Delete.24.png"));
        suajButton.setText("Sửa, xóa phòng");
        suajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suajButtonActionPerformed(evt);
            }
        });

        datPhongjButton.setBackground(new java.awt.Color(51, 154, 202));
        datPhongjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        datPhongjButton.setForeground(new java.awt.Color(51, 51, 0));
        datPhongjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Inipagi-Job-Seeker-Room-tag.24.png"));
        datPhongjButton.setText("  Đặt phòng     ");
        datPhongjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datPhongjButtonActionPerformed(evt);
            }
        });

        taoHoaDonjButton.setBackground(new java.awt.Color(51, 154, 202));
        taoHoaDonjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taoHoaDonjButton.setForeground(new java.awt.Color(51, 51, 0));
        taoHoaDonjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Erix-Subyarko-Medical-Invoice-Bill-Payment-Billing-Hospital.24.png"));
        taoHoaDonjButton.setText("  Tạo hóa đơn  ");
        taoHoaDonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taoHoaDonjButtonActionPerformed(evt);
            }
        });

        thoatjButton.setBackground(new java.awt.Color(51, 154, 202));
        thoatjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thoatjButton.setForeground(new java.awt.Color(51, 51, 0));
        thoatjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Hopstarter-Button-Button-Close.24.png"));
        thoatjButton.setText("    Thoát     ");
        thoatjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatjButtonActionPerformed(evt);
            }
        });

        allRoomjButton.setBackground(new java.awt.Color(51, 154, 202));
        allRoomjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        allRoomjButton.setForeground(new java.awt.Color(51, 51, 0));
        allRoomjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Icons8-Windows-8-Data-View-Details.24.png"));
        allRoomjButton.setText("   Xem phòng  ");
        allRoomjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRoomjButtonActionPerformed(evt);
            }
        });

        xemHoaDonjButton.setBackground(new java.awt.Color(51, 154, 202));
        xemHoaDonjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xemHoaDonjButton.setForeground(new java.awt.Color(51, 51, 0));
        xemHoaDonjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Microsoft-Fluentui-Emoji-Mono-See-No-Evil-Monkey.24.png"));
        xemHoaDonjButton.setText("  Xem hóa đơn");
        xemHoaDonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemHoaDonjButtonActionPerformed(evt);
            }
        });

        searchjButton.setBackground(new java.awt.Color(51, 154, 202));
        searchjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchjButton.setForeground(new java.awt.Color(51, 51, 0));
        searchjButton.setIcon(new javax.swing.ImageIcon("icon\\\\Paomedia-Small-N-Flat-Magnify.24.png"));
        searchjButton.setText("  Tìm kiếm    ");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        phongTrongjTable.setBackground(new java.awt.Color(204, 255, 255));
        phongTrongjTable.setForeground(new java.awt.Color(204, 0, 0));
        phongTrongjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(phongTrongjTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 124, 149));
        jLabel1.setText("            Danh sách phòng trống trong khách sạn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datPhongjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(thoatjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(xemHoaDonjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allRoomjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taoHoaDonjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(suajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(themPhongjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(themPhongjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(allRoomjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datPhongjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taoHoaDonjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xemHoaDonjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(thoatjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        QuanLyPhongjMenu.setBackground(new java.awt.Color(0, 255, 0));
        QuanLyPhongjMenu.setText("Quản lý phòng");

        ThemPhongjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Hopstarter-Button-Button-Add.24.png"));
        ThemPhongjMenuItem.setText("Thêm phòng");
        QuanLyPhongjMenu.add(ThemPhongjMenuItem);

        suaXoaPhongjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Hopstarter-Button-Button-Delete.24.png"));
        suaXoaPhongjMenuItem.setText("Sửa, xóa phòng");
        QuanLyPhongjMenu.add(suaXoaPhongjMenuItem);

        jMenuBar1.add(QuanLyPhongjMenu);

        XemThongTinjMenu.setText("Xem thông tin");

        donDatPhongjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Erix-Subyarko-Medical-Invoice-Bill-Payment-Billing-Hospital.24.png"));
        donDatPhongjMenuItem.setText("Xem đơn đặt phòng, tạo hóa đơn");
        XemThongTinjMenu.add(donDatPhongjMenuItem);

        allRoomjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Icons8-Windows-8-Data-View-Details.24.png"));
        allRoomjMenuItem.setText("Xem tất cả các phòng trong khách sạn");
        XemThongTinjMenu.add(allRoomjMenuItem);

        jMenuBar1.add(XemThongTinjMenu);

        jMenu1.setText("Đặt phòng");

        datPhongjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Inipagi-Job-Seeker-Room-tag.24.png"));
        datPhongjMenuItem.setText("Đặt phòng");
        jMenu1.add(datPhongjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Hóa đơn");

        xemHoaDonjMenuItem1.setIcon(new javax.swing.ImageIcon("icon\\\\Microsoft-Fluentui-Emoji-Mono-See-No-Evil-Monkey.24.png"));
        xemHoaDonjMenuItem1.setText("Xem hóa đơn");
        jMenu3.add(xemHoaDonjMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tìm kiếm");

        trangTimKiemjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Paomedia-Small-N-Flat-Magnify.24.png"));
        trangTimKiemjMenuItem.setText("Trang tìm kiếm");
        jMenu4.add(trangTimKiemjMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Thoát chương trình");

        exitjMenuItem.setIcon(new javax.swing.ImageIcon("icon\\\\Hopstarter-Button-Button-Close.24.png"));
        exitjMenuItem.setText("Oke");
        jMenu2.add(exitjMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suajButtonActionPerformed

    private void datPhongjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datPhongjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datPhongjButtonActionPerformed

    private void thoatjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thoatjButtonActionPerformed

    private void taoHoaDonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taoHoaDonjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taoHoaDonjButtonActionPerformed

    private void allRoomjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRoomjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allRoomjButtonActionPerformed

    private void xemHoaDonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemHoaDonjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xemHoaDonjButtonActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void themPhongjButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themPhongjButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_themPhongjButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomeView().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void addThemPhongListener(ActionListener listener) {
        ThemPhongjMenuItem.addActionListener(listener);
        themPhongjButton.addActionListener(listener);
    }
    
    public void addDatPhongListener(ActionListener listener) {
        datPhongjMenuItem.addActionListener(listener);
        datPhongjButton.addActionListener(listener);
    }
    
    public void addAllRoomListener(ActionListener listener) {
        allRoomjMenuItem.addActionListener(listener);
        allRoomjButton.addActionListener(listener);
    }
    
    public void addXemDonDatPhongListener(ActionListener listener) {
        donDatPhongjMenuItem.addActionListener(listener);
        taoHoaDonjButton.addActionListener(listener);
    }
    
    public void addExitProgramListener(ActionListener listener) {
        exitjMenuItem.addActionListener(listener);
    }
    
    public void addSuaXoaPhongListener(ActionListener listener) {
        suaXoaPhongjMenuItem.addActionListener(listener);
        suajButton.addActionListener(listener);
    }
    
    public void addXemHoaDonListener(ActionListener listener) {
        xemHoaDonjMenuItem1.addActionListener(listener);
        xemHoaDonjButton.addActionListener(listener);
    }
    
    public void addTimKiemListener(ActionListener listener) {
        trangTimKiemjMenuItem.addActionListener(listener);
        searchjButton.addActionListener(listener);
    }
    
    public void addThoatListener(ActionListener listener) {
        thoatjButton.addActionListener(listener);
    }
//    public void addThemPhongListener(ActionListener listener) {
//        LoginButton.addActionListener(listener);
//    }
    
    public static void changeColor(JPanel panel) {
        Timer timer = new Timer(10, new ActionListener() {
            Random rand = new Random();

            @Override
            public void actionPerformed(ActionEvent e) {
                panel.setBackground(new Color(rand.nextInt(256), rand.nextInt(256), rand.nextInt(256)));
            }
        });
        timer.start();
    }
    public void showTable() throws IOException, ClassNotFoundException {
        ThemPhongDao tpd = new ThemPhongDao();
        List<Phong> dsp = tpd.readPhongFromFile();
        List<Phong> phongTrong = new ArrayList<>();
        for(Phong p : dsp) {
            if(!p.isDaDuocDat()) {
                phongTrong.add(p);
            }
        }
        if(phongTrong.isEmpty()) {
            String[] newColumnTitles = {"", "", "", ""};
            DefaultTableModel model = (DefaultTableModel) phongTrongjTable.getModel();
            model.setColumnIdentifiers(newColumnTitles);
            model.setRowCount(0);
            
        }else{
            String[] newColumnTitles = {"Số phòng", "Loại phòng", "Số giường", "Giá(/h)"};
            DefaultTableModel model = (DefaultTableModel) phongTrongjTable.getModel();
            model.setColumnIdentifiers(newColumnTitles);
            model.setRowCount(0);
            for(Phong p : phongTrong) {
                Object[] row = new Object[4];
                row[0] = p.getSoPhong();
                row[1] = p.getLoaiPhong();
                row[2] = p.getSoLuongGiuong();
                row[3] = String.valueOf(p.getGia());
                model.addRow(row);
            }
        }
    }

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QuanLyPhongjMenu;
    private javax.swing.JMenuItem ThemPhongjMenuItem;
    private javax.swing.JMenu XemThongTinjMenu;
    private javax.swing.JButton allRoomjButton;
    private javax.swing.JMenuItem allRoomjMenuItem;
    private javax.swing.JButton datPhongjButton;
    private javax.swing.JMenuItem datPhongjMenuItem;
    private javax.swing.JMenuItem donDatPhongjMenuItem;
    private javax.swing.JMenuItem exitjMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable phongTrongjTable;
    private javax.swing.JButton searchjButton;
    private javax.swing.JMenuItem suaXoaPhongjMenuItem;
    private javax.swing.JButton suajButton;
    private javax.swing.JButton taoHoaDonjButton;
    private javax.swing.JButton themPhongjButton;
    private javax.swing.JButton thoatjButton;
    private javax.swing.JMenuItem trangTimKiemjMenuItem;
    private javax.swing.JButton xemHoaDonjButton;
    private javax.swing.JMenuItem xemHoaDonjMenuItem1;
    // End of variables declaration//GEN-END:variables
}
