/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author CNG;
 */
public class ThemPhongView extends javax.swing.JFrame {

    /**
     * Creates new form DatPhongView
     */
    public ThemPhongView() {
        initComponents();
        //this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        giaJLabel = new javax.swing.JLabel();
        loaiPhongjComboBox = new javax.swing.JComboBox<>();
        soLuongGiuongjComboBox = new javax.swing.JComboBox<>();
        TieudeJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        xacNhanjButton = new javax.swing.JButton();
        soPhongJLabel = new javax.swing.JLabel();
        canclejButton = new javax.swing.JButton();
        loaiPhongJLabel = new javax.swing.JLabel();
        soPhongjFormattedTextField = new javax.swing.JFormattedTextField();
        soLuongGiuongJLabel = new javax.swing.JLabel();
        giajFormattedTextField = new javax.swing.JFormattedTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        giaJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        giaJLabel.setText("Giá (tính theo giờ)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 61, 0, 0);
        jPanel2.add(giaJLabel, gridBagConstraints);

        loaiPhongjComboBox.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        loaiPhongjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng Standard", "Phòng Superior", "Phòng Deluxe", "Phòng Executive" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 513;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 18, 0, 0);
        jPanel2.add(loaiPhongjComboBox, gridBagConstraints);

        soLuongGiuongjComboBox.setEditable(true);
        soLuongGiuongjComboBox.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        soLuongGiuongjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 592;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 18, 0, 0);
        jPanel2.add(soLuongGiuongjComboBox, gridBagConstraints);

        TieudeJLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TieudeJLabel.setForeground(new java.awt.Color(146, 66, 222));
        TieudeJLabel.setText("Thêm Phòng Vào Khách Sạn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 33, 0, 0);
        jPanel2.add(TieudeJLabel, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 907;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 0, 0);
        jPanel2.add(jSeparator1, gridBagConstraints);

        xacNhanjButton.setBackground(new java.awt.Color(51, 255, 0));
        xacNhanjButton.setText("Xác nhận");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(93, 40, 36, 0);
        jPanel2.add(xacNhanjButton, gridBagConstraints);

        soPhongJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soPhongJLabel.setText("Số Phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(89, 61, 0, 0);
        jPanel2.add(soPhongJLabel, gridBagConstraints);

        canclejButton.setBackground(new java.awt.Color(51, 255, 51));
        canclejButton.setText("Cancle");
        canclejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclejButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(93, 465, 36, 0);
        jPanel2.add(canclejButton, gridBagConstraints);

        loaiPhongJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loaiPhongJLabel.setText("Loại Phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 61, 0, 0);
        jPanel2.add(loaiPhongJLabel, gridBagConstraints);

        soPhongjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        soPhongjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soPhongjFormattedTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 600;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(90, 18, 0, 0);
        jPanel2.add(soPhongjFormattedTextField, gridBagConstraints);

        soLuongGiuongJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soLuongGiuongJLabel.setText("Số lượng giường");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 61, 0, 0);
        jPanel2.add(soLuongGiuongJLabel, gridBagConstraints);

        giajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        giajFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giajFormattedTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 600;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 18, 0, 0);
        jPanel2.add(giajFormattedTextField, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canclejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canclejButtonActionPerformed

    private void soPhongjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soPhongjFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soPhongjFormattedTextFieldActionPerformed

    private void giajFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giajFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giajFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemPhongView().setVisible(true);
            }
        });
    }
    public int getSoPhong()
    {
        return Integer.parseInt(soPhongjFormattedTextField.getText().toString());
    }
    
    public String getLoaiPhong() {
        return loaiPhongjComboBox.getSelectedItem().toString();
    }
    
    public int getSoLuongGiuong() {
        return Integer.parseInt(soLuongGiuongjComboBox.getSelectedItem().toString());
    }
    
    public double getGia() {
        return Double.parseDouble(giajFormattedTextField.getText().toString());
    }
    
    public boolean hopLeTenPhong() {
        String soPhong = soPhongjFormattedTextField.getText();
        if (soPhong == null || "".equals(soPhong.trim())) {
            return false;
        }
        try {
            int phongNumber = Integer.parseInt(soPhong);
            if(phongNumber<0) return false;
        } catch (NumberFormatException e) {
        return false;
        }
        return true;
    }
    
    public boolean hopLeGia() {
    String s = giajFormattedTextField.getText();
        if (s == null || "".equals(s.trim())) {
            return false;
        }
        try {
            double gia = Double.parseDouble(s);
            if(gia<0) return false;
        } catch (NumberFormatException e) {
        return false;
        }
        return true;
} 
    
    public void addCancleListener(ActionListener listener) {
       canclejButton.addActionListener(listener);
    }
    
    
    public void addXacNhanListener(ActionListener listener) {
        xacNhanjButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TieudeJLabel;
    private javax.swing.JButton canclejButton;
    private javax.swing.JLabel giaJLabel;
    private javax.swing.JFormattedTextField giajFormattedTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loaiPhongJLabel;
    private javax.swing.JComboBox<String> loaiPhongjComboBox;
    private javax.swing.JLabel soLuongGiuongJLabel;
    private javax.swing.JComboBox<String> soLuongGiuongjComboBox;
    private javax.swing.JLabel soPhongJLabel;
    private javax.swing.JFormattedTextField soPhongjFormattedTextField;
    private javax.swing.JButton xacNhanjButton;
    // End of variables declaration//GEN-END:variables
}
