/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import qlks.dao.DatPhongDao;
import qlks.dao.ThemPhongDao;
import qlks.entity.Datphong;
import qlks.entity.Hoadon;
import qlks.entity.Phong;

/**
 *
 * @author CNG;
 */
public class XemDonDatPhongView extends javax.swing.JFrame {

    /**
     * Creates new form XemDonDatPhongView
     */
    public XemDonDatPhongView() {
        initComponents();
        //this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        xemChiTietjDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        phongTrongjTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tenKhachHangjTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        OkejButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressjTextField = new javax.swing.JTextField();
        phonejTextField = new javax.swing.JTextField();
        emailjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        idDatPhongjTextField = new javax.swing.JTextField();
        thoiGianDatPhongjTextField = new javax.swing.JTextField();
        taoHoaDonjDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        phongTrongjTable1 = new javax.swing.JTable();
        addressjTextField1 = new javax.swing.JTextField();
        phonejTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailjTextField1 = new javax.swing.JTextField();
        tenKhachHangjTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        idDatPhongjTextField1 = new javax.swing.JTextField();
        OkejButton1 = new javax.swing.JButton();
        thoiGianDatPhongjTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ngayTraPhongjTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tongtienjTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        maHoaDonjTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donDatPhongjTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        xemChiTietjButton = new javax.swing.JButton();
        canclejButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        xemChiTietjDialog.setAlwaysOnTop(true);
        xemChiTietjDialog.setAutoRequestFocus(false);
        xemChiTietjDialog.setBackground(new java.awt.Color(204, 255, 255));
        xemChiTietjDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        xemChiTietjDialog.setMinimumSize(new java.awt.Dimension(1100, 500));
        xemChiTietjDialog.setModal(true);

        phongTrongjTable.setBackground(new java.awt.Color(204, 255, 255));
        phongTrongjTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phongTrongjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Số lượng giường", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        phongTrongjTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(phongTrongjTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 11, 57));
        jLabel3.setText("Danh sách phòng mà khách hàng đó đặt");

        OkejButton.setBackground(new java.awt.Color(51, 255, 51));
        OkejButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OkejButton.setText("Oke");
        OkejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkejButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên khách hàng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ khách hàng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Thời gian đặt phòng:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email:");

        addressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextFieldActionPerformed(evt);
            }
        });

        emailjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ID Đặt phòng");

        javax.swing.GroupLayout xemChiTietjDialogLayout = new javax.swing.GroupLayout(xemChiTietjDialog.getContentPane());
        xemChiTietjDialog.getContentPane().setLayout(xemChiTietjDialogLayout);
        xemChiTietjDialogLayout.setHorizontalGroup(
            xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemChiTietjDialogLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(xemChiTietjDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thoiGianDatPhongjTextField))
                    .addGroup(xemChiTietjDialogLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xemChiTietjDialogLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(xemChiTietjDialogLayout.createSequentialGroup()
                                .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addressjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                    .addComponent(tenKhachHangjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                    .addComponent(emailjTextField)
                                    .addComponent(phonejTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemChiTietjDialogLayout.createSequentialGroup()
                                .addGap(0, 141, Short.MAX_VALUE)
                                .addComponent(idDatPhongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(xemChiTietjDialogLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(OkejButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemChiTietjDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(31, 31, 31))
        );
        xemChiTietjDialogLayout.setVerticalGroup(
            xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemChiTietjDialogLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemChiTietjDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xemChiTietjDialogLayout.createSequentialGroup()
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(idDatPhongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tenKhachHangjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(addressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phonejTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(xemChiTietjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(thoiGianDatPhongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(OkejButton)
                        .addGap(24, 24, 24))))
        );

        taoHoaDonjDialog.setMinimumSize(new java.awt.Dimension(1100, 600));
        taoHoaDonjDialog.setModal(true);

        phongTrongjTable1.setBackground(new java.awt.Color(204, 255, 255));
        phongTrongjTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phongTrongjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Số lượng giường", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        phongTrongjTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        phongTrongjTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(phongTrongjTable1);

        addressjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Danh sách phòng mà khách hàng đó đặt");

        emailjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextField1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("ID Đặt phòng");

        OkejButton1.setBackground(new java.awt.Color(51, 255, 51));
        OkejButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OkejButton1.setText("Oke");
        OkejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkejButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tên khách hàng:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Địa chỉ khách hàng:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Phone:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Thời gian đặt phòng:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Email:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Thời gian trả phòng");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Tổng tiền phải trả");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Mã hóa đơn");

        javax.swing.GroupLayout taoHoaDonjDialogLayout = new javax.swing.GroupLayout(taoHoaDonjDialog.getContentPane());
        taoHoaDonjDialog.getContentPane().setLayout(taoHoaDonjDialogLayout);
        taoHoaDonjDialogLayout.setHorizontalGroup(
            taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createSequentialGroup()
                .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taoHoaDonjDialogLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(taoHoaDonjDialogLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(taoHoaDonjDialogLayout.createSequentialGroup()
                                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addressjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                            .addComponent(tenKhachHangjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                            .addComponent(phonejTextField1)
                                            .addComponent(emailjTextField1, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createSequentialGroup()
                                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel11))
                                        .addGap(52, 52, 52)
                                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idDatPhongjTextField1)
                                            .addComponent(maHoaDonjTextField)))))))
                    .addGroup(taoHoaDonjDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(7, 7, 7)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thoiGianDatPhongjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(ngayTraPhongjTextField)
                            .addComponent(tongtienjTextField))))
                .addGap(18, 18, 18)
                .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(79, 79, 79))))
            .addGroup(taoHoaDonjDialogLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(OkejButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        taoHoaDonjDialogLayout.setVerticalGroup(
            taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maHoaDonjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taoHoaDonjDialogLayout.createSequentialGroup()
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(idDatPhongjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tenKhachHangjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(addressjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phonejTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailjTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(thoiGianDatPhongjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ngayTraPhongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(taoHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tongtienjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(OkejButton1)
                        .addGap(24, 24, 24))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        donDatPhongjTable.setBackground(new java.awt.Color(204, 255, 255));
        donDatPhongjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Đặt phòng", "Tên khách hàng", "Phone", "Danh sách các phòng đã đặt ", "Ngày đặt phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donDatPhongjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(donDatPhongjTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Danh sách các đơn đặt phòng");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Tạo hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        xemChiTietjButton.setBackground(new java.awt.Color(51, 255, 51));
        xemChiTietjButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        xemChiTietjButton.setText("Xem chi tiết");
        xemChiTietjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemChiTietjButtonActionPerformed(evt);
            }
        });

        canclejButton.setBackground(new java.awt.Color(51, 255, 51));
        canclejButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        canclejButton.setText("Cancle");
        canclejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(canclejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(xemChiTietjButton)
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xemChiTietjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canclejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xemChiTietjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemChiTietjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xemChiTietjButtonActionPerformed

    private void OkejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkejButtonActionPerformed

    private void addressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextFieldActionPerformed

    private void emailjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addressjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextField1ActionPerformed

    private void emailjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextField1ActionPerformed

    private void OkejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkejButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkejButton1ActionPerformed

    private void canclejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canclejButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showTable() throws IOException, ClassNotFoundException {
        DatPhongDao dpd = new DatPhongDao();
        List<Datphong> ddp = dpd.readDatPhongFromFile();
        if(ddp==null) {
            JOptionPane.showMessageDialog(this, "bi null");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) donDatPhongjTable.getModel();
        for (Datphong dp : ddp) {
            if (dp != null) {
                List<Phong> dsp = dp.getPh();
                String strNumbers = "";
                for (int i = 0; i < dsp.size(); i++) {
                    if (i > 0) {
                        strNumbers += ", ";
                    }
                    strNumbers += Integer.toString(dsp.get(i).getSoPhong());
                }

            Object[] row = new Object[5];
            row[0] = dp.getIdDatPhong();
            row[1] = dp.getKH().getHoten();
            row[2] = "0"+dp.getKH().getSdt();
            row[3] = strNumbers;
            row[4] = dp.getThoiGianDatPhong();
            model.addRow(row);
        }
    }

    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) donDatPhongjTable.getModel();
        model.setRowCount(0);
    }
    
    public boolean checkNgay() throws IOException, ClassNotFoundException {
        String maDP = getSelectedRowData();
        DatPhongDao dpd = new DatPhongDao();
        List<Datphong> dsDP = dpd.readDatPhongFromFile();
        Date ngayHienTai = new Date();
        for(Datphong d : dsDP) {
            if(d.getIdDatPhong().equals(maDP)) {
                Date ngayDatPhong = d.getThoiGianDatPhong();
                if (ngayHienTai.compareTo(ngayDatPhong) > 0) {
                    System.out.println("ngayhientai lớn hơn ngaydatphong");
                    return true;
                } else {
                    System.out.println("ngayhientai nho hon ngay dat phong");
                    return false;
                }
            }
        }
        return false; // vi khong co phong nao duoc chon
        //ham chi hoat dong dung khi co dong duoc chon nho dieu nay phai long vao trong dieu kien cua su kien nhan button nha
    }
    
    public void traPhong(Datphong dp) throws IOException, ClassNotFoundException {
        List<Phong> dsPhong = dp.getPh();
        ThemPhongDao tp = new ThemPhongDao();
        List<Phong> dsAllPhong = tp.readPhongFromFile();
        for(Phong a : dsAllPhong) {
            for(Phong b : dsPhong) {
                if(b.getSoPhong()==a.getSoPhong()) {
                    a.setDaDuocDat(false);
                }
            }
        }
        tp.saveDanhSachPhong(dsAllPhong);
    }
    
    public void showHoaDonDialog(Hoadon hoadon) {
        maHoaDonjTextField.setText(hoadon.getMshd());
        idDatPhongjTextField1.setText(hoadon.getDatphong().getIdDatPhong());
        tenKhachHangjTextField1.setText(hoadon.getDatphong().getKH().getHoten());
        addressjTextField1.setText(hoadon.getDatphong().getKH().getAddress());
        phonejTextField1.setText("0"+String.valueOf(hoadon.getDatphong().getKH().getSdt()));
        emailjTextField1.setText(hoadon.getDatphong().getKH().getEmail());
        thoiGianDatPhongjTextField1.setText(String.valueOf(hoadon.getDatphong().getThoiGianDatPhong()));
        ngayTraPhongjTextField.setText(String.valueOf(hoadon.getNgay()));
        tongtienjTextField.setText(String.valueOf(hoadon.getTongTien()));
        DefaultTableModel model = (DefaultTableModel) phongTrongjTable1.getModel();
        model.setRowCount(0);
        List<Phong> phong =hoadon.getDatphong().getPh();
            for (Phong p : phong) {
                Object[] row = new Object[4];
                row[0] = p.getSoPhong();
                row[1] = p.getLoaiPhong();
                row[2] = p.getSoLuongGiuong();
                row[3] = p.getGia();
                model.addRow(row);
            }
    }
    
    public void xoaDonDatPhong(Datphong dp) throws IOException, ClassNotFoundException {
        DatPhongDao dpd = new DatPhongDao();
        List<Datphong> donDatPhong = dpd.readDatPhongFromFile();
        if (donDatPhong.size() == 1 && donDatPhong.contains(dp)) {
            donDatPhong.clear();
        } else {
            donDatPhong.remove(dp);
        }
                    Iterator<Datphong> iterator = donDatPhong.iterator();
                    while (iterator.hasNext()) {
                        Datphong p = iterator.next();
                        if (p.getIdDatPhong().equals(dp.getIdDatPhong())) {
                            iterator.remove();
                        }
                    }
        dpd.saveListDatPhong(donDatPhong);
    }

    
    public void showDonDatPhong() throws IOException, ClassNotFoundException {
        taoHoaDonjDialog.setVisible(false);
    }
    
    
    public void addCancleListener(ActionListener listener) {
        canclejButton.addActionListener(listener);
    }
    
    public void addOkeHoaDonListener(ActionListener listener) {
        OkejButton1.addActionListener(listener);
    }
    
    public void addTaoHoaDonListener(ActionListener listener) {
        jButton1.addActionListener(listener);
    }
    
    public void addOkeListener(ActionListener listener) {
        OkejButton.addActionListener(listener);
    }
   
    public void addXemChiTietListener(ActionListener listener) {
        xemChiTietjButton.addActionListener(listener);
    }
    
    public void centerDialog(JDialog dialog) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) (screenSize.getWidth() / 2 - dialog.getSize().getWidth() / 2);
        int centerY = (int) (screenSize.getHeight() / 2 - dialog.getSize().getHeight() / 2);
        dialog.setLocation(centerX, centerY);
    }
    
    public void showDialogCenter() {
        centerDialog(xemChiTietjDialog);
        xemChiTietjDialog.setVisible(true);
    }
    
    public void showHoaDonDialogCenter(Hoadon hoadon) {
        centerDialog(taoHoaDonjDialog);
        showHoaDonDialog(hoadon);
        taoHoaDonjDialog.setVisible(true);
    }
    
    
    public void showDonDatPhongTable() {
        centerDialog(xemChiTietjDialog);
        xemChiTietjDialog.setVisible(false);
    }
    
    public boolean isSelectedRow() {
        if (donDatPhongjTable.getSelectedRow() == -1) {
    // Không có dòng nào được chọn trong bảng
            return false;
        } else {
            // Đã có dòng được chọn trong bảng
            return true;
        }
    }
    
    public String getSelectedRowData() {
        int selectedRowIndex = donDatPhongjTable.getSelectedRow();

        if (selectedRowIndex < 0) {
            // Không có hàng nào được chọn
            return "";
        }

        DefaultTableModel model = (DefaultTableModel) donDatPhongjTable.getModel();
        Object rowData = model.getValueAt(selectedRowIndex, 0);

        // Dữ liệu của cột đầu tiên của hàng được chọn
        
        return rowData.toString();
    }
    
    public Datphong layDonDatPhong() throws IOException, ClassNotFoundException {
        String maDP = getSelectedRowData();
        DatPhongDao dpd = new DatPhongDao();
        List<Datphong> dsp = dpd.readDatPhongFromFile();
        for(Datphong d : dsp) {
            if(maDP.equals(d.getIdDatPhong())) {
                return d;
            }
        }
        return null;
    }
    
    
    
    
    public void showDialogContent(String maDP) throws IOException, ClassNotFoundException {
        DatPhongDao dpd = new DatPhongDao();
        List<Datphong> dsp = dpd.readDatPhongFromFile();
        DefaultTableModel model = (DefaultTableModel) phongTrongjTable.getModel();

        // Xóa toàn bộ dữ liệu hiện có trong bảng
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
    }
    
    for(Datphong d : dsp) {
        if(maDP.equals(d.getIdDatPhong())) {
            idDatPhongjTextField.setText(d.getIdDatPhong());
            idDatPhongjTextField.setEditable(false);
            tenKhachHangjTextField.setText(d.getKH().getHoten());
            tenKhachHangjTextField.setEditable(false);
            addressjTextField.setText(d.getKH().getAddress());
            addressjTextField.setEditable(false);
            phonejTextField.setText("0"+d.getKH().getSdt());
            phonejTextField.setEditable(false);
            emailjTextField.setText(d.getKH().getEmail());
            emailjTextField.setEditable(false);
            thoiGianDatPhongjTextField.setText(String.valueOf(d.getThoiGianDatPhong()));
            thoiGianDatPhongjTextField.setEditable(false);
            List<Phong> phong =d.getPh();
            for (Phong p : phong) {
                Object[] row = new Object[4];
                row[0] = p.getSoPhong();
                row[1] = p.getLoaiPhong();
                row[2] = p.getSoLuongGiuong();
                row[3] = p.getGia();
                model.addRow(row);
            }
        }
    }
}



    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemDonDatPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemDonDatPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemDonDatPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemDonDatPhongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemDonDatPhongView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkejButton;
    private javax.swing.JButton OkejButton1;
    private javax.swing.JTextField addressjTextField;
    private javax.swing.JTextField addressjTextField1;
    private javax.swing.JButton canclejButton;
    private javax.swing.JTable donDatPhongjTable;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField emailjTextField1;
    private javax.swing.JTextField idDatPhongjTextField;
    private javax.swing.JTextField idDatPhongjTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maHoaDonjTextField;
    private javax.swing.JTextField ngayTraPhongjTextField;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.JTextField phonejTextField1;
    private javax.swing.JTable phongTrongjTable;
    private javax.swing.JTable phongTrongjTable1;
    private javax.swing.JDialog taoHoaDonjDialog;
    private javax.swing.JTextField tenKhachHangjTextField;
    private javax.swing.JTextField tenKhachHangjTextField1;
    private javax.swing.JTextField thoiGianDatPhongjTextField;
    private javax.swing.JTextField thoiGianDatPhongjTextField1;
    private javax.swing.JTextField tongtienjTextField;
    private javax.swing.JButton xemChiTietjButton;
    private javax.swing.JDialog xemChiTietjDialog;
    // End of variables declaration//GEN-END:variables
}
