/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import qlks.dao.HoaDonDao;
import qlks.entity.Hoadon;
import qlks.entity.Phong;

/**
 *
 * @author CNG;
 */
public class XemHoaDonView extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonView
     */
    public XemHoaDonView() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        chiTietHoaDonjDialog = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ngayTraPhongjTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        idDatPhongjTextField1 = new javax.swing.JTextField();
        tongtienjTextField = new javax.swing.JTextField();
        OkejButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        phongTrongjTable1 = new javax.swing.JTable();
        thoiGianDatPhongjTextField1 = new javax.swing.JTextField();
        maHoaDonjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addressjTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phonejTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        emailjTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tenKhachHangjTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hoaDonjTable1 = new javax.swing.JTable();
        canclejButton1 = new javax.swing.JButton();
        xemChiTietjButton = new javax.swing.JButton();

        chiTietHoaDonjDialog.setMinimumSize(new java.awt.Dimension(1100, 600));
        chiTietHoaDonjDialog.setModal(true);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Thời gian trả phòng");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("ID Đặt phòng");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Tổng tiền phải trả");

        OkejButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OkejButton1.setText("Oke");
        OkejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkejButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Mã hóa đơn");

        phongTrongjTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phongTrongjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phòng", "Loại phòng", "Số lượng giường", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        phongTrongjTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(phongTrongjTable1);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tên khách hàng:");

        addressjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressjTextField1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Địa chỉ khách hàng:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Phone:");

        jLabel10.setText("Danh sách phòng mà khách hàng đó đặt");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Thời gian đặt phòng:");

        emailjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailjTextField1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Email:");

        javax.swing.GroupLayout chiTietHoaDonjDialogLayout = new javax.swing.GroupLayout(chiTietHoaDonjDialog.getContentPane());
        chiTietHoaDonjDialog.getContentPane().setLayout(chiTietHoaDonjDialogLayout);
        chiTietHoaDonjDialogLayout.setHorizontalGroup(
            chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chiTietHoaDonjDialogLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(chiTietHoaDonjDialogLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(chiTietHoaDonjDialogLayout.createSequentialGroup()
                                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(chiTietHoaDonjDialogLayout.createSequentialGroup()
                                                .addComponent(emailjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(phonejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addressjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tenKhachHangjTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(idDatPhongjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                            .addComponent(maHoaDonjTextField)))))))
                    .addGroup(chiTietHoaDonjDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(7, 7, 7)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thoiGianDatPhongjTextField1)
                            .addComponent(ngayTraPhongjTextField)
                            .addComponent(tongtienjTextField))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(99, 99, 99))
            .addGroup(chiTietHoaDonjDialogLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(OkejButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chiTietHoaDonjDialogLayout.setVerticalGroup(
            chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maHoaDonjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chiTietHoaDonjDialogLayout.createSequentialGroup()
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(idDatPhongjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tenKhachHangjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(addressjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phonejTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailjTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(thoiGianDatPhongjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ngayTraPhongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(chiTietHoaDonjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tongtienjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(OkejButton1)
                        .addGap(24, 24, 24))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 90, 96));
        jLabel1.setText("Danh sách các hóa đơn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 283, 52, 287);
        jPanel1.add(jLabel1, gridBagConstraints);

        hoaDonjTable1.setBackground(new java.awt.Color(204, 255, 255));
        hoaDonjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Ngày vào ", "Ngày ra", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hoaDonjTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        hoaDonjTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(hoaDonjTable1);

        canclejButton1.setBackground(new java.awt.Color(51, 255, 51));
        canclejButton1.setText("Cancle");
        canclejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclejButton1ActionPerformed(evt);
            }
        });

        xemChiTietjButton.setBackground(new java.awt.Color(51, 255, 51));
        xemChiTietjButton.setText("Xem chi tiết");
        xemChiTietjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemChiTietjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canclejButton1)
                .addGap(76, 76, 76)
                .addComponent(xemChiTietjButton)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canclejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xemChiTietjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canclejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclejButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canclejButton1ActionPerformed

    private void xemChiTietjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemChiTietjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xemChiTietjButtonActionPerformed

    private void OkejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkejButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkejButton1ActionPerformed

    private void addressjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressjTextField1ActionPerformed

    private void emailjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailjTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void addCancleListener(ActionListener listener) {
       canclejButton1.addActionListener(listener);
    }
    
    public void addXemChiTietListener(ActionListener listener) {
       xemChiTietjButton.addActionListener(listener);
    }
    
    public void addOkeListener(ActionListener listener) {
       OkejButton1.addActionListener(listener);
    }
    
    public void showTable() throws IOException, ClassNotFoundException {
        DefaultTableModel model = (DefaultTableModel) hoaDonjTable1.getModel();
        
        HoaDonDao hdd = new HoaDonDao();
        List<Hoadon> dsHoaDon = hdd.readHoaDonFromFile();
        for(Hoadon h : dsHoaDon){
            Object[] row = new Object[5];
            row[0] = h.getMshd();
            row[1] = h.getDatphong().getKH().getHoten();
            row[2] = String.valueOf(h.getDatphong().getThoiGianDatPhong());
            row[3] = String.valueOf(h.getNgay());
            row[4] = h.getTongTien();
            model.addRow(row);
        }
    }
    
    public boolean isSelectedRow() {
        if (hoaDonjTable1.getSelectedRow() == -1) {
    // Không có dòng nào được chọn trong bảng
            return false;
        } else {
            // Đã có dòng được chọn trong bảng
            return true;
        }
    }
    
    public String getSelectedRowData() {
        int selectedRowIndex = hoaDonjTable1.getSelectedRow();

        if (selectedRowIndex < 0) {
            // Không có hàng nào được chọn
            return "";
        }

        DefaultTableModel model = (DefaultTableModel) hoaDonjTable1.getModel();
        Object rowData = model.getValueAt(selectedRowIndex, 0);

        // Dữ liệu của cột đầu tiên của hàng được chọn
        
        return rowData.toString();
    }
    
    public Hoadon layHoaDon() throws IOException, ClassNotFoundException {
        HoaDonDao hdd = new HoaDonDao();
        List<Hoadon> dsHD = hdd.readHoaDonFromFile();
        for(Hoadon h : dsHD) {
            if(h.getMshd().equals(getSelectedRowData())) {
                return h;
            }
        }
        return null;
    }
    
    public void centerDialog(JDialog dialog) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int centerX = (int) (screenSize.getWidth() / 2 - dialog.getSize().getWidth() / 2);
        int centerY = (int) (screenSize.getHeight() / 2 - dialog.getSize().getHeight() / 2);
        dialog.setLocation(centerX, centerY);
    }
    
    public void showDialogCenter() {
        centerDialog(chiTietHoaDonjDialog);
        chiTietHoaDonjDialog.setVisible(true);
    }
    
    public void unshowDialog() {
        chiTietHoaDonjDialog.setVisible(false);
    }
    
    
    public void showHoaDonDialog(Hoadon hoadon) {
        maHoaDonjTextField.setText(hoadon.getMshd());
        idDatPhongjTextField1.setText(hoadon.getDatphong().getIdDatPhong());
        tenKhachHangjTextField1.setText(hoadon.getDatphong().getKH().getHoten());
        addressjTextField1.setText(hoadon.getDatphong().getKH().getAddress());
        phonejTextField1.setText("0"+String.valueOf(hoadon.getDatphong().getKH().getSdt()));
        emailjTextField1.setText(hoadon.getDatphong().getKH().getEmail());
        thoiGianDatPhongjTextField1.setText(String.valueOf(hoadon.getDatphong().getThoiGianDatPhong()));
        ngayTraPhongjTextField.setText(String.valueOf(hoadon.getNgay()));
        tongtienjTextField.setText(String.valueOf(hoadon.getTongTien()));
        DefaultTableModel model = (DefaultTableModel) phongTrongjTable1.getModel();
        model.setRowCount(0);
        List<Phong> phong =hoadon.getDatphong().getPh();
            for (Phong p : phong) {
                Object[] row = new Object[4];
                row[0] = p.getSoPhong();
                row[1] = p.getLoaiPhong();
                row[2] = p.getSoLuongGiuong();
                row[3] = p.getGia();
                model.addRow(row);
            }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemHoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemHoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemHoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemHoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemHoaDonView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkejButton1;
    private javax.swing.JTextField addressjTextField1;
    private javax.swing.JButton canclejButton1;
    private javax.swing.JDialog chiTietHoaDonjDialog;
    private javax.swing.JTextField emailjTextField1;
    private javax.swing.JTable hoaDonjTable1;
    private javax.swing.JTextField idDatPhongjTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maHoaDonjTextField;
    private javax.swing.JTextField ngayTraPhongjTextField;
    private javax.swing.JTextField phonejTextField1;
    private javax.swing.JTable phongTrongjTable1;
    private javax.swing.JTextField tenKhachHangjTextField1;
    private javax.swing.JTextField thoiGianDatPhongjTextField1;
    private javax.swing.JTextField tongtienjTextField;
    private javax.swing.JButton xemChiTietjButton;
    // End of variables declaration//GEN-END:variables
}
